#!/bin/bash

###################################################
# start bluetooth services if not already running #
###################################################

trap "sudo rm -f /home/pi/MagicMirror/data/running" 2

if [ -d /opt/bt-speaker ]
then
        echo "Bluetooth services previously initialized [CREDIT: LukasJapan]"
else
        echo "Initializing Bluetooth services [CREDIT: LukasJapan]"
        sudo curl -s https://raw.githubusercontent.com/lukasjapan/bt-speaker/master/install.sh | sudo bash
fi

####################
# start the mirror #
####################

cd MagicMirror

cat MagicMirrorText

sudo python Main.py